all:	clean comp run waveverdi

test:   comp run

clean:
	\rm -rf simv* csrc* *.log *.fsdb *.rc *.key verdi_config_file verdiLog *.conf
comp:
	vcs -f build.cud -sverilog -kdb +vcs+fsdbon \
	-sdf typ:switch_test_GLS.u_switch_4port.u_gate:switch_4port_no_cg_f_with_compile_final.sdf
	#vcs -f build.cud -sverilog -kdb +vcs+fsdbon

run:
	qrsh -V -cwd -b y -q normal ./simv 2>&1 | tee log
	#qrsh -V -cwd -b y -q sim_normal ./simv +ntb_random_seed_automatic 2>&1 | tee log
waveverdi: 	
	verdi -ssf novas.fsdb
coverage:
	verdi -cov -covdir simv.vdb
